x-common-variables: &common-variables
  POSTGRES_USER: admin
  POSTGRES_PASSWORD: password
  POSTGRES_DB: koshelekDB

services:
  api:
    image: dmitryleonov/koshelektesttaskapi
    container_name: KoshelekTestTaskApi
    environment:
      <<: *common-variables
      POSTGRES_HOST: postgres
      SEQ_SERVER_URL: http://seq:5341
    ports:
      - 8082:80
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./api.dockerfile
    depends_on:
      - postgres
      - seq

  client:
    image: dmitryleonov/koshelektesttaskclient
    container_name: KoshelekTestTaskClient
    ports:
      - 82:80
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./client.dockerfile
      
  seq:
    image: datalust/seq
    container_name: KoshelekTestTaskSeq
    environment:
      - ACCEPT_EULA=Y
    ports:
      - 5341:80
    restart: unless-stopped
      
  postgres:
    image: dmitryleonov/koshelektesttaskpostgres
    container_name: KoshelekTestTaskPostgreSQL
    environment: *common-variables
    ports:
      - 5432:5432
    build:
      context: .
      dockerfile: ./postgres.dockerfile
    restart: unless-stopped